# Generated by Django 4.2.1 on 2023-07-31 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_remove_content_featured_image_content_content_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='vimeo_video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
