# Generated by Django 4.2.1 on 2023-08-15 14:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_tag_postcontent_alter_contentimage_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('audio_file', models.FileField(upload_to='upload')),
                ('category', models.ManyToManyField(blank=True, to='content.category')),
                ('tags', models.ManyToManyField(to='content.tag')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
