# Generated by Django 4.2.1 on 2023-08-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_remove_exercisefile_exercise_delete_exercise_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('methods', models.ManyToManyField(related_name='exercises', to='exercises.exercisemethod')),
            ],
        ),
    ]
