# Generated by Django 4.2.1 on 2023-09-03 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_userexerciseplaylist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexerciseplaylist',
            name='playlist',
            field=models.TextField(default='[]'),
        ),
    ]
