# Generated by Django 4.2.1 on 2023-07-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_content_date_created_content_date_update_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='featured_image',
        ),
        migrations.AddField(
            model_name='content',
            name='content_image',
            field=models.ImageField(blank=True, null=True, upload_to='content_images/'),
        ),
        migrations.AddField(
            model_name='content',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='content_thumbnails/'),
        ),
    ]
