# Generated by Django 4.2.1 on 2023-07-31 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_content_vimeo_video_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='vimeo_video_url',
            new_name='embed_video_url',
        ),
    ]
