# Generated by Django 4.2.1 on 2023-08-04 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_contentimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='content_image',
        ),
    ]
