# Generated by Django 4.2.1 on 2023-08-12 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_category_content_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
