# Generated by Django 4.2.1 on 2023-08-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_audiocontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiocontent',
            name='audio_file',
            field=models.FileField(upload_to='audio'),
        ),
    ]
